### ISSUE TITLE
dce break

### ISSUE THREAD

**Issue by postite** [massiveinteractive/mmvc#15]
i have this runtime error in js wwhen using dce full 

Uncaught TypeError: Cannot read property 'nonEmpty' of undefined Signal.hx:150
msignal.Signal.registrationPossible Signal.hx:150
msignal.Signal.registerListener Signal.hx:135
msignal.Signal.add Signal.hx:65
mmvc.base.CommandMap.mapSignal CommandMap.hx:78
mmvc.base.CommandMap.mapSignalClass CommandMap.hx:50
amibe.app.AppContext.$extend.startup AppContext.hx:34
mmvc.impl.Context.checkAutoStartup Context.hx:220
mmvc.impl.Context.set_contextView Context.hx:128
mmvc.impl.Context Context.hx:104
amibe.app.AppContext AppContext.hx:15
(anonymous function)

i tried to mark all my classes with @:keep .. but no luck .. i know msignal works well usually with dce. 
the problem occurs with commandmapping in Appcontext

**Comment by dpeek** [comment]
Hi @postite,
Sorry that this issue got ignored completely, we've struggled with DCE and dependency injection as well – the two just don't seem to play very well in general with out a lot of manual @:keep metadata.

I'm going to try and tackle the problem in the next major version of minject using some macro helpers to keep things that get mapped in to the injector.

I've created an issue to track this here:
https://github.com/massiveinteractive/minject/issues/33
