### ISSUE TITLE
commands triggered by anything not just signals

### ISSUE THREAD

**Issue by jozefchutka** [massiveinteractive/mmvc#17]
We hit some major issues when using signals for triggering commands. Because signals are singletons and so its hard to maintain response in case the signal.dispatch is executed in loop, not to mention unnecessary memory footprint of having a custom signal for each command...

The solution is rather very simple. It uses TriggerMap to map any trigger (class) to any command. Each command can be dispatched with a specific instance of trigger so its much easier to handle related "response", and much more easier to obtain trigger instance/value in command:
```haxe
package mmvc.impl;

import haxe.ds.StringMap;

import mmvc.api.ICommand;
import mmvc.impl.Actor;

class TriggerMap extends Actor
{
	var map:StringMap<Class<ICommand>>;

	public function new()
	{
		map = new StringMap<Class<ICommand>>();

		super();
	}

	public function dispatch(trigger:Dynamic)
	{
		var triggerClass = Type.getClass(trigger);
		var triggerClassName = Type.getClassName(triggerClass);
		if(!map.exists(triggerClassName))
			throw "Command for trigger " + triggerClassName + " is not defined.";

		injector.mapValue(triggerClass, trigger, "trigger");
		var command = injector.instantiate(map.get(triggerClassName));
		injector.unmap(triggerClass, "trigger");

		command.execute();
	}

	public function mapCommand(trigger:Class<Dynamic>, command:Class<ICommand>)
	{
		var triggerClassName = Type.getClassName(trigger);
		if(map.exists(triggerClassName))
			throw "Command for trigger " + triggerClassName + " is already defined.";

		map.set(triggerClassName, command);
	}

	public function unmapCommand(trigger:Class<Dynamic>)
	{
		var triggerClassName = Type.getClassName(trigger);
		map.remove(triggerClassName);
	}
}
```

The Command implementation in this case needs to be tweaked and Signal injection removed:
```haxe
package mmvc.impl;

import minject.Injector;

import mmvc.api.ICommand;
import mmvc.api.ICommandMap;
import mmvc.api.IMediatorMap;
import mmvc.api.IViewContainer;

class Command implements ICommand
{
	@inject public var contextView:IViewContainer;
	@inject public var commandMap:ICommandMap;
	@inject public var injector:Injector;
	@inject public var mediatorMap:IMediatorMap;

	public function new():Void{}
	public function execute(){}
}
```

and finally the usage. Lets map some commands in context:
```haxe
injector.mapSingleton(TriggerMap);
var triggerMap:TriggerMap = injector.getInstance(TriggerMap);

triggerMap.mapCommand(String, StringCommand);
triggerMap.mapCommand(Int, IntCommand);
triggerMap.mapCommand(MyVO, VOCommand);
```

triggering in mediator:
```haxe
class MyMediator extends Mediator
{
	@inject public var triggerMap:TriggerMap;
	override function onRegister()
	{
		triggerMap.dispatch("hello world");
	}
}
```

```haxe
class StringCommand extends Command
{
	@inject("trigger") public var trigger:String;

	override function execute()
	{
		trace("StringCommand executed = " + trigger);
	}
}

class IntCommand extends Command
{
	@inject("trigger") public var trigger:Int;

	override function execute()
	{
		trace("StringCommand executed = " + trigger);
	}
}

class VOCommand extends Command
{
	@inject("trigger") public var trigger:MyVO;

	override function execute()
	{
		trace("StringCommand executed = " + Std.string(trigger));
	}
}
```

this approach lets you implement triggerMap on project level but if we decide to implement it on mmvc level that would be even more awesome

**Comment by haysclark** [comment]
Will TriggerMaps be added to MMVC?

**Comment by jozefchutka** [comment]
hi @haysclark 
good job with implementing it in your repo. just checked and looks good. few points:
- you may want to use ITriggerMap in your customized context
- here is how you can make trigger injection working for your command
```haxe
@:generic
class TriggeredCommand<TTrigger> implements ICommand
{
    // ... keep your injections here plus:
    @inject("trigger") public var trigger:TTrigger;
```

- do not forget to add support to your mediators
```haxe
class TriggeringMediator<T> extends Mediator<T>
{
	@inject
	public var triggerMap:TriggerMap;
	// consider exposing proxying dispatch* functions right here on mediator base class
}
```

**Comment by dpeek** [comment]
This all looks great! @jozefchutka do you want to pull this together into a PR with docs/tests so we can put it into the next release?

**Comment by jozefchutka** [comment]
I can do that. how do we go with Command class? Do we keep the original one and I add TriggeredCommand? The original Command can not be used with trigger as signal injection would not get satisfied...

**Comment by dpeek** [comment]
I think we add TriggeredCommand, Commands often use the dispatching signal reference (particularly with ResponderSignals)

**Comment by jozefchutka** [comment]
PR here https://github.com/massiveinteractive/mmvc/pull/20

**Comment by haysclark** [comment]
@jozefchutka Sorry about not being around for a couple days.  I'm looking forward to see this feature added.
