### ISSUE TITLE
Type not found : minject.ClassMap

### ISSUE THREAD

**Issue by darmie** [massiveinteractive/mmvc#35]
I tried to build my app, and I get this error:

/usr/local/lib/haxe/lib/mmvc/1,6,3/mmvc/base/CommandMap.hx:27: characters 8-24 : Type not found : minject.ClassMap

**Comment by darmie** [comment]
Same problem with `minject.Injector`

**Comment by elsassph** [comment]
Sorry, you need to install `minject` version 1.x to work with `mmvc` 1.x.
