### ISSUE TITLE
Which version of mmvc is compatible with minject 2.0?

### ISSUE THREAD

**Issue by darmie** [massiveinteractive/mmvc#36]
I am having trouble compiling my project due to missing classes in minject which mmvc depends on.

`/usr/local/lib/haxe/lib/mmvc/1,6,3/mmvc/base/CommandMap.hx:27: characters 8-24 : Type not found : minject.ClassMap`

**Comment by elsassph** [comment]
Latest 1.x (1.6.3 as of now) will be compatible.

**Comment by darmie** [comment]
@elsassph  thanks. 

But I am still getiing `Type not found` errors.

`/usr/local/lib/haxe/lib/mmvc/1,6,3/mmvc/base/CommandMap.hx:26: characters 8-24 : Type not found : minject.Injector`

**Comment by elsassph** [comment]
Sorry I meant you need to install `minject` 1.x - latest published 1.x seem to be 1.6.1

**Comment by darmie** [comment]
Thank you. It's resolved.
